In [5]:
import numpy as np
r=int(input("enter the no of rows of first matrix"))
c=int(input("enter the no of columns of first matrix"))
print("\nenter the matrix elements\n")
entry=list(map(int,input().split()))
arr=np.array(entry).reshape(r,c)
print("\ninput arrays\n",arr)
m=int(input("enter the no of rows of second matrix"))
n=int(input("enter the no of columns of second matrix"))
print("\nenter the matrix elements\n")
entry2=list(map(int,input().split()))
arr1=np.array(entry2).reshape(m,n)
print("\ninput arrays\n",arr1)
#1. Dot Product
print("\ndot product of given matrixes:\n")
print(np.dot(arr,arr1))
#2.transpose
print("\ntranspose of 2 matrices\n",arr.transpose())
print(arr1.transpose())
#3.Trace
print("\ntrace of first matrix:\n",np.trace(arr))
print("\ntrace of second matrix:\n",np.trace(arr1))
#Rank
print("\nrank of first matrix:\n",np.linalg.matrix_rank(arr))
print("\nrank of second matrix:\n",np.linalg.matrix_rank(arr1))
#Determinant
print("\ndeterminant of first matrix:\n",np.linalg.det(arr))
print("\ndeterminant of second matrix:\n",np.linalg.det(arr1))
#Inverse
print("\ninverse of first matrix:\n",np.linalg.inv(arr))
print("\ninverse of second matrix:\n",np.linalg.inv(arr1))
#eigen values and eigen vectors
w, v = np.linalg.eig(arr)
x, y = np.linalg.eig(arr1)
print("\neigen values and eigen vectors of first matrix:\n")
print("\neigen value:\n",w)
print("\neigen vectors:\n",v)
print("\neigen values and eigen vectors of second matrix:\n")
print("\neigen value:\n",x)
print("\neigen value:\n",y)

enter the no of rows of first matrix2 
enter the no of columns of first matrix2

enter the matrix elements

1 4 2 5 

input arrays
 [[1 4]
 [2 5]]
enter the no of rows of second matrix2
enter the no of columns of second matrix2

enter the matrix elements

 4 5 8 9 

input arrays
 [[4 5]
 [8 9]]

dot product of given matrixes:

[[36 41]
 [48 55]]

transpose of 2 matrices
 [[1 2]
 [4 5]]
[[4 8]
 [5 9]]

trace of first matrix:
 6

trace of second matrix:
 13

rank of first matrix:
 2

rank of second matrix:
 2

determinant of first matrix:
 -2.9999999999999996

determinant of second matrix:
 -3.999999999999999

inverse of first matrix:
 [[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]

inverse of second matrix:
 [[-2.25  1.25]
 [ 2.   -1.  ]]

eigen values and eigen vectors of first matrix:


eigen value:
 [-0.46410162  6.46410162]

eigen vectors:
 [[-0.9390708  -0.59069049]
 [ 0.34372377 -0.80689822]]

eigen values and eigen vectors of second matrix:


eigen value:
 [-0.30073525 13